[build]
command = "go build -o server ./cmd/server"
publish = "."

[context.production.environment]
GO_VERSION = "1.20"

[build.environment]
NETLIFY_USE_YARN = "true"
GO_IMPORT_PATH = "github.com/endrilickollari/remote-server-api"
