[build]
publish = "build"
functions = "functions"

[context.production.environment]
GO_VERSION = "1.19"

[build.environment]
NETLIFY_USE_YARN = "true"
GO_IMPORT_PATH = "github.com/endrilickollari/remote-server-api"
