basePath: /
definitions:
  auth.LoginRequest:
    properties:
      ip:
        type: string
      password:
        type: string
      port:
        type: string
      username:
        type: string
    required:
    - ip
    - password
    - port
    - username
    type: object
  auth.LoginResponse:
    properties:
      token:
        type: string
    type: object
  docker.Container:
    properties:
      command:
        type: string
      container_id:
        type: string
      created_on:
        type: string
      image:
        type: string
      names:
        type: string
      ports:
        type: string
      status:
        type: string
    type: object
  response.Response:
    properties:
      data: {}
      error:
        type: string
      success:
        type: boolean
    type: object
  server.CPUInfo:
    properties:
      address_sizes:
        type: string
      apicid:
        type: string
      bogomips:
        type: string
      cache_alignment:
        type: string
      cache_size:
        type: string
      clflush_size:
        type: string
      core_id:
        type: string
      cpu_cores:
        type: string
      cpu_family:
        type: string
      cpu_mhz:
        type: string
      cpuid_level:
        type: string
      flags:
        type: string
      fpu:
        type: string
      fpu_exception:
        type: string
      initial_apicid:
        type: string
      microcode:
        type: string
      model:
        type: string
      model_name:
        type: string
      physical_id:
        type: string
      power_management:
        type: string
      processor:
        type: string
      siblings:
        type: string
      stepping:
        type: string
      vendor_id:
        type: string
      wp:
        type: string
    type: object
  server.DiskUsage:
    properties:
      available:
        type: string
      filesystem:
        type: string
      mounted_on:
        type: string
      size:
        type: string
      use_percentage:
        type: string
      used:
        type: string
    type: object
  server.FileSystemEntry:
    properties:
      group:
        type: string
      is_hidden:
        description: Whether the file/directory is hidden (starts with .)
        type: boolean
      last_modified:
        type: string
      mime_type:
        description: MIME type of the file (only for files)
        type: string
      name:
        type: string
      owner:
        type: string
      path:
        type: string
      permissions:
        type: string
      preview:
        description: Preview of text files (first few lines)
        type: string
      size:
        description: Size in bytes, only applicable for files
        type: integer
      type:
        description: '"file", "directory", "symlink", etc.'
        type: string
    type: object
  server.FileSystemListing:
    properties:
      entries:
        items:
          $ref: '#/definitions/server.FileSystemEntry'
        type: array
      path:
        type: string
      recursive:
        type: boolean
    type: object
  server.Library:
    properties:
      architecture:
        type: string
      name:
        type: string
      status:
        type: string
      version:
        type: string
    type: object
  server.ProcessInfo:
    properties:
      command:
        type: string
      cpu_consumption:
        type: string
      process_id:
        type: string
      rss:
        type: string
      started:
        type: string
      stat:
        type: string
      time:
        type: string
      tty:
        type: string
      user:
        type: string
      vsz:
        type: string
    type: object
  server.ServerDetails:
    properties:
      hostname:
        type: string
      kernel_version:
        type: string
      os:
        type: string
      uptime:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for Cerberus - Remote Server Management
  title: Cerberus API
  version: 2.0.0
paths:
  /docker/container-details:
    get:
      consumes:
      - application/json
      description: Retrieves information about Docker containers from the server
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Docker container information retrieved successfully
          schema:
            items:
              $ref: '#/definitions/docker.Container'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Get Docker container information
      tags:
      - docker
  /filesystem/details:
    get:
      consumes:
      - application/json
      description: Retrieves detailed information about a specific file or directory
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: Path to the file or directory
        in: query
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: File details retrieved successfully
          schema:
            $ref: '#/definitions/server.FileSystemEntry'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Get file details
      tags:
      - filesystem
  /filesystem/list:
    get:
      consumes:
      - application/json
      description: Retrieves a listing of files and directories at the specified path
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: Path to list (defaults to /)
        in: query
        name: path
        type: string
      - default: false
        description: Whether to list recursively
        in: query
        name: recursive
        type: boolean
      - default: false
        description: Whether to include hidden files/directories
        in: query
        name: include_hidden
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: File system listing retrieved successfully
          schema:
            $ref: '#/definitions/server.FileSystemListing'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: List files and directories
      tags:
      - filesystem
  /filesystem/search:
    get:
      consumes:
      - application/json
      description: Searches for files matching a pattern in the specified directory
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: Path to search in
        in: query
        name: path
        required: true
        type: string
      - description: Search pattern (glob or regex)
        in: query
        name: pattern
        required: true
        type: string
      - default: 10
        description: Maximum search depth
        in: query
        name: max_depth
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Search results retrieved successfully
          schema:
            items:
              $ref: '#/definitions/server.FileSystemEntry'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Search for files
      tags:
      - filesystem
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates user against an SSH server and returns a JWT token
        for subsequent API requests
      parameters:
      - description: SSH login credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged in and token generated
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Failed to connect to SSH server or generate token
          schema:
            $ref: '#/definitions/response.Response'
      summary: Login to SSH and generate JWT token
      tags:
      - authentication
  /server-details:
    get:
      consumes:
      - application/json
      description: Retrieves basic server information like hostname, OS, kernel version,
        etc.
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Server details retrieved successfully
          schema:
            $ref: '#/definitions/server.ServerDetails'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Get basic server details
      tags:
      - server
  /server-details/cpu-info:
    get:
      consumes:
      - application/json
      description: Retrieves detailed CPU information from the server
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: CPU information retrieved successfully
          schema:
            items:
              $ref: '#/definitions/server.CPUInfo'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Get CPU information
      tags:
      - server
  /server-details/disk-usage:
    get:
      consumes:
      - application/json
      description: Retrieves disk usage information from the server
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Disk usage information retrieved successfully
          schema:
            items:
              $ref: '#/definitions/server.DiskUsage'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Get disk usage information
      tags:
      - server
  /server-details/libraries:
    get:
      consumes:
      - application/json
      description: Retrieves information about installed libraries and packages on
        the server
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Installed libraries information retrieved successfully
          schema:
            items:
              $ref: '#/definitions/server.Library'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Get installed libraries information
      tags:
      - server
  /server-details/running-processes:
    get:
      consumes:
      - application/json
      description: Retrieves information about running processes on the server
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Running processes information retrieved successfully
          schema:
            items:
              $ref: '#/definitions/server.ProcessInfo'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Get running processes information
      tags:
      - server
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
