name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: cerebrus:latest
          outputs: type=docker,dest=cerebrus.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cerebrus-docker-image
          path: cerebrus.tar